function defaultCatalog_() {
  return [
    ["greenhouse", "stripe", "Stripe"],
    ["greenhouse", "databricks", "Databricks"],
    ["greenhouse", "airbnb", "Airbnb"],
    ["greenhouse", "cloudflare", "Cloudflare"],
    ["greenhouse", "gitlab", "GitLab"],
    ["greenhouse", "figma", "Figma"],
    ["greenhouse", "janestreet", "Jane Street"],
    ["greenhouse", "point72", "Point72"],
    ["ashby", "openai", "OpenAI"],
    ["ashby", "snowflake", "Snowflake"],
    ["ashby", "notion", "Notion"],
    ["ashby", "ramp", "Ramp"],
    ["ashby", "cursor", "Cursor"],
    ["ashby", "perplexity", "Perplexity"],
    ["ashby", "linear", "Linear"],
    ["ashby", "posthog", "PostHog"],
    ["ashby", "motherduck", "MotherDuck"],
    ["ashby", "hex", "Hex"],
    ["lever", "palantir", "Palantir"],
    ["lever", "wealthfront", "Wealthfront"],
    ["smartrecruiters", "NielsenIQ", "NielsenIQ"],
    ["lever", "caseware", "Caseware"],
    ["ashby", "wealthsimple", "Wealthsimple"],
    ["greenhouse", "instacart", "Instacart"],
    ["ashby", "1password", "1Password"],
    ["greenhouse", "hootsuite", "Hootsuite"],
    ["ashby", "hopper", "Hopper"],
    ["ashby", "lightspeed", "Lightspeed"],
    ["greenhouse", "d2l", "D2L"],
    ["greenhouse", "stackadapt", "StackAdapt"],
    ["greenhouse", "ritual", "Ritual"],
    ["ashby", "thinkific", "Thinkific"],
    ["ashby", "koho", "KOHO"],
    ["greenhouse", "datadog", "Datadog"],
    ["greenhouse", "hubspot", "HubSpot"],
    ["greenhouse", "mongodb", "MongoDB"],
    ["greenhouse", "intercom", "Intercom"],
    ["greenhouse", "asana", "Asana"],
    ["greenhouse", "dropbox", "Dropbox"],
    ["greenhouse", "coinbase", "Coinbase"],
    ["greenhouse", "twilio", "Twilio"],
  ].map(function (row) {
    return { source: row[0], token: row[1], company: row[2], enabled: true };
  });
}
